title: Just In Time For...
author: Justin Wu
email: justin.wu1@live.com
description: > # this means to ignore newlines until "baseurl:"
  My personal blog that documents my coding journey and personal interests.
theme: minima
# social links
github_username:  JWuWuTang

show_excerpts: true # set to false to remove excerpts on the homepage
